FCBHDBP-586 creating endpoint to delete days from a plan
fullstacklabs/dbp pull request #1
Opened 2024-07-29 19:44 UTC by marcvictorpassarelli

# Description

## Issue Link

[FCBHDBP-586](https://fullstacklabs.atlassian.net/browse/FCBHDBP-586)

## How Do I QA This

## Screenshots (if appropriate)

2024-07-30 19:31 UTC, vichugofsl requested changes
See the above comments

2024-07-30 19:31 UTC, vichugofsl commented on app/Http/Controllers/Plan/PlansController.php
> +            $deleted_days = PlanDay::whereIn('id', $days_ids)->where('plan_id', $plan->id);
@marcvictorpassarelli Let's create a static method to wrap up the entire logic for removing the plan days using the days_id and plan ID. You can check an example in the following and let me give an example:

https://github.com/fullstacklabs/dbp/blob/develop/app/Models/Plan/UserPlan.php#L138

```php
    // LOCATION: dbp/app/Models/Plan/PlanDay.php
    /**
     * Remove the Plan Days records attached to a Plan...........
     *
     * @param int $plan_id
     * @param array $plan_day_ids
     *
     * @return bool
     */
    public static function removePlanDaysByPlanId(int $plan_id, array $plan_day_ids): bool
    {
        try {
            \DB::transaction(function () use ($plan_id, $plan_day_ids) {
                $deleted_days = PlanDay::whereIn('id', $plan_day_ids)->where('plan_id', $plan_id);
                $playlists_ids = $deleted_days->pluck('playlist_id')->unique();
                $playlists = Playlist::whereIn('id', $playlists_ids);
                $deleted_days->delete();
                $playlists->delete();
            });
            return true;
        } catch (\Exception $e) {
            \Log::error('Failed to remove plan days', ['plan_id' => $plan_id, 'plan_day_ids' => $plan_day_ids, 'exception' => $e]);
            return false;
        }
    }
```
Marc, if you can see the above, it is using the concept of statement transactions. It is recommended to use this when you are performing more than one database operation and each operation depends on another. This ensures that if an operation fails, the state of the database can be reverted to the initial state before starting the first operation, avoiding partially completed operations.

You can check the concept of database transactions here: https://laravel.com/docs/11.x/database#database-transactions or https://www.javatpoint.com/mysql-transaction

2024-07-30 19:31 UTC, vichugofsl commented on app/Http/Controllers/Plan/PlansController.php
> +        return $this->reply('Plan days were succesfully deleted');
@marcvictorpassarelli Here you can validate and return a 500 code if the new method returns false, as the plan days could not be removed, something like:

```php
        if (!PlanDay::removePlanDaysByPlanId(...)) {
            return $this->setStatusCode(SymfonyResponse::HTTP_INTERNAL_SERVER_ERROR)->replyWithError("Plan Days can't be deleted");
        }
        
        return $this->reply('Plan days were succesfully deleted');
```

2024-07-30 19:31 UTC, vichugofsl commented on routes/api.php
> +Route::name('v4_internal_plans_days.delete')
@marcvictorpassarelli As you have added a new endpoint, we need to run the following command to update the API documentation. After you run the command, you should check if the file `dbp/public/openapi.json` has been updated.

```shell
php artisan openApi:generate
```

2024-07-30 22:26 UTC, marcvictorpassarelli commented on app/Http/Controllers/Plan/PlansController.php
> +            return $this->setStatusCode(401)->replyWithError(trans('api.projects_users_not_connected'));
Noted. I changed the hard coded numbers for the constants

2024-07-31 20:20 UTC, vichugofsl approved these changes

2024-07-31 20:26 UTC, vichugofsl approved these changes
LGTM

2024-07-31 20:32 UTC, merged